version: '3'

services:
  mentors-search:
    build:
      dockerfile: mentor-search.Dockerfile
      context: .
    command:
      - python3
      - -m
      - flask
      - run
      - --host=0.0.0.0
      - --port=5041
    environment:
      PORT: 5041
      FLASK_DEBUG: 1
      FLASK_APP: 'src/controllers/mentor-search/intelligent-search.py'
      FLASK_ENV: 'development'
#      MONGODB_STAGING_URI: 'mongodb://mapout:mapout@localhost/mapout'
      MONGODB_URI: 'mongodb+srv://mapout:mapout@mapoutdb.hj2on.mongodb.net/mapout-staging?retryWrites=true&w=majority'
#      MONGODB_STAGING_URI: 'mongodb+srv://mapout:mapout@mapoutdb.hj2on.mongodb.net/mapout?retryWrites=true&w=majority'
      DATABASE: 'mapout-staging'
#      DATABASE: 'mapout'
    ports:
      - "5041:5041"
    expose:
      - "5041"
    volumes:
      - .:/home/app

  mentors-search-indexer:
    build:
      context: .
      dockerfile: mentor-search-indexer.Dockerfile
    environment:
      MONGODB_URI: 'mongodb+srv://mapout:mapout@mapoutdb.hj2on.mongodb.net/mapout-staging?retryWrites=true&w=majority'
      DATABASE: 'mapout-staging'
    volumes:
      - .:/home/app

  skills:
    build:
      dockerfile: skills.Dockerfile
      context: .
    command:
      - npm
      - run
      - start:dev
    environment:
      NODE_ENV: 'development'
      APP_NAME: 'MapOut Skills'
      PORT: 4041
      MONGODB_URI: 'mongodb+srv://mapout:mapout@mapoutdb.hj2on.mongodb.net/mapout-staging?retryWrites=true&w=majority'
#      MONGODB_STAGING_URI: 'mongodb://mapout:mapout@localhost/mapout'
      DATABASE: 'mapout-staging'
#      DATABASE: 'mapout'
    ports:
      - "4041:4041"
    expose:
      - "4041"
    volumes:
      - .:/home/app
