//Data from https://degree.studentnews.eu/
module.exports = [
  { degree: "B. Accty", level: 3 },
  { degree: "B.A", level: 3 },
  { degree: "B.AS", level: 3 },
  { degree: "B.ASc", level: 3 },
  { degree: "B.Acc", level: 3 },
  { degree: "B.Acy", level: 3 },
  { degree: "B.Arch", level: 3 },
  { degree: "B.B.A", level: 3 },
  { degree: "B.C.A", level: 3 },
  { degree: "B.Com", level: 3 },
  { degree: "B.Des", level: 3 },
  { degree: "B.Design", level: 3 },
  { degree: "B.E", level: 3 },
  { degree: "B.Ed", level: 3 },
  { degree: "B.Eng", level: 3 },
  { degree: "B.F.A", level: 3 },
  { degree: "B.L", level: 3 },
  { degree: "B.MS", level: 3 },
  { degree: "B.Mus", level: 3 },
  { degree: "B.S", level: 3 },
  { degree: "B.Sc", level: 3 },
  { degree: "B.Soc.Sc", level: 3 },
  { degree: "B.Soc.Sci", level: 3 },
  { degree: "B.Tech", level: 3 },
  { degree: "B.TECH", level: 3 },
  { degree: "B.tech", level: 3 },
  { degree: "Btech", level: 3 },
  { degree: "B.Th", level: 3 },
  { degree: "BA", level: 3 },
  { degree: "BA(Econ)", level: 3 },
  { degree: "BASc", level: 3 },
  { degree: "BAcc", level: 3 },
  { degree: "BAppSc", level: 3 },
  { degree: "BArch", level: 3 },
  { degree: "BBA", level: 3 },
  { degree: "BBA(Econ)", level: 3 },
  { degree: "BCA", level: 3 },
  { degree: "BChD", level: 3 },
  { degree: "BD", level: 3 },
  { degree: "BDIV", level: 3 },
  { degree: "BDS", level: 3 },
  { degree: "BDentS", level: 3 },
  { degree: "BDes", level: 3 },
  { degree: "BE", level: 3 },
  { degree: "BEc", level: 3 },
  { degree: "BEconSc", level: 3 },
  { degree: "BEd", level: 3 },
  { degree: "BEng", level: 3 },
  { degree: "BFA", level: 3 },
  { degree: "BFin", level: 3 },
  { degree: "BHSc", level: 3 },
  { degree: "BM", level: 3 },
  { degree: "BMBCh(Oxon)", level: 3 },
  { degree: "BMBS", level: 3 },
  { degree: "BMSc", level: 3 },
  { degree: "BMedSc", level: 3 },
  { degree: "BMedSci", level: 3 },
  { degree: "BMid", level: 3 },
  { degree: "BMidWif", level: 3 },
  { degree: "BMus", level: 3 },
  { degree: "BNurs", level: 3 },
  { degree: "BOptom", level: 3 },
  { degree: "BOst", level: 3 },
  { degree: "BOstMed", level: 3 },
  { degree: "BS", level: 3 },
  { degree: "BSAS", level: 3 },
  { degree: "BSSc(Econ)", level: 3 },
  { degree: "BSW", level: 3 },
  { degree: "BSc", level: 3 },
  { degree: "BSc(Econ)", level: 3 },
  { degree: "BScEcon", level: 3 },
  { degree: "BSci(Med)", level: 3 },
  { degree: "BSocSc", level: 3 },
  { degree: "BTEC", level: 3 },
  { degree: "BTechEd", level: 3 },
  { degree: "BTh", level: 3 },
  { degree: "BTheol", level: 3 },
  { degree: "BVM&S", level: 3 },
  { degree: "BVMBVS", level: 3 },
  { degree: "BVMS", level: 3 },
  { degree: "BVMedSci", level: 3 },
  { degree: "BVSC", level: 3 },
  { degree: "BVSc", level: 3 },
  { degree: "BVetMed", level: 3 },
  { degree: "Bachelor of Accountancy", level: 3 },
  { degree: "Bachelor of Applied Science", level: 3 },
  { degree: "Bachelor of Architecture", level: 3 },
  { degree: "Bachelor of Arts", level: 3 },
  { degree: "Bachelor of Business Administration", level: 3 },
  { degree: "Bachelor of Clinical Optometry", level: 3 },
  { degree: "Bachelor of Dental Surgery", level: 3 },
  { degree: "Bachelor of Design", level: 3 },
  { degree: "Bachelor of Divinity", level: 3 },
  { degree: "Bachelor of Economics", level: 3 },
  { degree: "Bachelor of Education", level: 3 },
  { degree: "Bachelor of Engineering", level: 3 },
  { degree: "Bachelor of Finance", level: 3 },
  { degree: "Bachelor of Fine Arts", level: 3 },
  { degree: "Bachelor of Health Science", level: 3 },
  { degree: "Bachelor of Laws", level: 3 },
  { degree: "Bachelor of Medical Sciences", level: 3 },
  { degree: "Bachelor of Medicine", level: 3 },
  { degree: "Bachelor of Medicine, Bachelor of Surgery", level: 3 },
  { degree: "Bachelor of Midwifery", level: 3 },
  { degree: "Bachelor of Music", level: 3 },
  { degree: "Bachelor of Nursing", level: 3 },
  { degree: "Bachelor of Osteopathy", level: 3 },
  { degree: "Bachelor of Science", level: 3 },
  { degree: "Bachelor of Social Science", level: 3 },
  { degree: "Bachelor of Social Work", level: 3 },
  { degree: "Bachelor of Technological Education", level: 3 },
  { degree: "Bachelor of Technology", level: 3 },
  { degree: "Bachelor of Theology", level: 3 },
  { degree: "Bachelor of Veterinary Medicine", level: 3 },
  { degree: "Bachelor of Veterinary Medicine and Surgery", level: 3 },
  { degree: "Bachelor of Veterinary Science", level: 3 },
  { degree: "Bachelor's", level: 3 },
  { degree: "Bachelor’s", level: 3 },
  { degree: "Bachelors", level: 3 },
  { degree: "BChir", level: 3 },
  { degree: "Cert ED", level: 1 },
  { degree: "Cert.HE", level: 1 },
  { degree: "CertED", level: 1 },
  { degree: "Certificate of Higher Education", level: 1 },
  { degree: "Ch.M", level: 4 },
  { degree: "ClinPsyD", level: 5 },
  { degree: "D.B.A", level: 5 },
  { degree: "DArts", level: 5 },
  { degree: "DBEnv", level: 5 },
  { degree: "DCaM", level: 5 },
  { degree: "DChiro", level: 5 },
  { degree: "DClinDent", level: 5 },
  { degree: "DClinP", level: 5 },
  { degree: "DClinPsy", level: 5 },
  { degree: "DClinPsych", level: 5 },
  { degree: "DClinRes", level: 5 },
  { degree: "DCommEd", level: 5 },
  { degree: "DCounsPsych", level: 5 },
  { degree: "DCounsPych", level: 5 },
  { degree: "DCrimJ", level: 5 },
  { degree: "DDSc", level: 5 },
  { degree: "DDes", level: 5 },
  { degree: "DEd", level: 5 },
  { degree: "DEdChPsy", level: 5 },
  { degree: "DEdPsy", level: 5 },
  { degree: "DForensPsy", level: 5 },
  { degree: "DHSc", level: 5 },
  { degree: "DHealth", level: 5 },
  { degree: "DHealthPsy", level: 5 },
  { degree: "DLitt", level: 5 },
  { degree: "DM", level: 5 },
  { degree: "DMin", level: 5 },
  { degree: "DMus", level: 5 },
  { degree: "DNursSc", level: 5 },
  { degree: "DPhil", level: 5 },
  { degree: "DProf", level: 5 },
  { degree: "DPsych", level: 5 },
  { degree: "DSc", level: 5 },
  { degree: "DSocSci", level: 5 },
  { degree: "DSyRM", level: 5 },
  { degree: "DThM", level: 5 },
  { degree: "DUniv", level: 5 },
  { degree: "DVetMed", level: 5 },
  { degree: "DipHE", level: 2 },
  { degree: "Diploma", level: 2 },
  { degree: "Diploma in the Advanced Study of Education", level: 2 },
  { degree: "Diploma of Higher Education", level: 2 },
  { degree: "Doctor of Art", level: 5 },
  { degree: "Doctor of Biomedical Science", level: 5 },
  { degree: "Doctor of Built Environment", level: 5 },
  { degree: "Doctor of Business Administration", level: 5 },
  { degree: "Doctor of Chiropractic", level: 5 },
  { degree: "Doctor of Civil Law", level: 5 },
  { degree: "Doctor of Clinical Dentistry", level: 5 },
  { degree: "Doctor of Clinical Practice", level: 5 },
  { degree: "Doctor of Clinical Psychology", level: 5 },
  { degree: "Doctor of Clinical Research", level: 5 },
  { degree: "Doctor of Coaching and Mentoring", level: 5 },
  { degree: "Doctor of Community Learning & Development", level: 5 },
  { degree: "Doctor of Counselling Psychology", level: 5 },
  { degree: "Doctor of Criminal Justice", level: 5 },
  { degree: "Doctor of Dental Medicine", level: 5 },
  { degree: "Doctor of Dental Surgery or Orthodontics", level: 5 },
  { degree: "Doctor of Dentistry or Doctor of Divinity", level: 5 },
  { degree: "Doctor of Design", level: 5 },
  { degree: "Doctor of Education", level: 5 },
  { degree: "Doctor of Educational Psychology", level: 5 },
  { degree: "Doctor of Educational and Child Psychology", level: 5 },
  { degree: "Doctor of Engineering", level: 5 },
  { degree: "Doctor of Enterprise", level: 5 },
  { degree: "Doctor of Forensic Clinical Psychology", level: 5 },
  { degree: "Doctor of Forensic Psychology", level: 5 },
  { degree: "Doctor of Forensic Psychology Practice", level: 5 },
  { degree: "Doctor of Health", level: 5 },
  { degree: "Doctor of Health Psychology", level: 5 },
  { degree: "Doctor of Health Science", level: 5 },
  { degree: "Doctor of Jurisprudence", level: 5 },
  { degree: "Doctor of Laws", level: 5 },
  { degree: "Doctor of Letters or Doctor of Literature", level: 5 },
  { degree: "Doctor of Medicine", level: 5 },
  { degree: "Doctor of Ministry", level: 5 },
  { degree: "Doctor of Music", level: 5 },
  { degree: "Doctor of Nursing Science", level: 5 },
  { degree: "Doctor of Philosophy", level: 5 },
  {
    degree: "Doctor of Physical Therapy or Doctor of Practical Theology",
    level: 5
  },
  { degree: "Doctor of Professional Studies", level: 5 },
  { degree: "Doctor of Psychology", level: 5 },
  { degree: "Doctor of Public Health", level: 5 },
  { degree: "Doctor of Science", level: 5 },
  { degree: "Doctor of Security Risk Management", level: 5 },
  { degree: "Doctor of Social Science", level: 5 },
  { degree: "Doctor of Social Work", level: 5 },
  { degree: "Doctor of Theology", level: 5 },
  { degree: "Doctor of Theology and Ministry", level: 5 },
  { degree: "Doctor of Veterinary Medicine", level: 5 },
  { degree: "Doctor of Veterinary Science", level: 5 },
  { degree: "Doctor of the University", level: 5 },
  { degree: "Dr.P.H", level: 5 },
  { degree: "DrPH", level: 5 },
  { degree: "DrPS", level: 5 },
  { degree: "EMBA", level: 4 },
  { degree: "Ed.M", level: 4 },
  { degree: "EdChPsychD", level: 5 },
  { degree: "EdD", level: 5 },
  { degree: "EngD", level: 5 },
  { degree: "EntD", level: 5 },
  { degree: "Executive MBA", level: 4 },
  { degree: "FDArts", level: 2 },
  { degree: "FDEd", level: 2 },
  { degree: "FDEng", level: 2 },
  { degree: "FDs", level: 2 },
  { degree: "FdA", level: 2 },
  { degree: "FdEd", level: 2 },
  { degree: "FdSc", level: 2 },
  { degree: "ForenClinPsyD", level: 5 },
  { degree: "ForenPsyD", level: 5 },
  { degree: "Foundation Degree in Learning Support", level: 2 },
  { degree: "Foundation degree", level: 2 },
  { degree: "Foundation of Arts (Foundation degree)", level: 2 },
  { degree: "Foundation of Engineering (Foundation degree)", level: 2 },
  { degree: "Foundation of Sciences (Foundation degree)", level: 2 },
  { degree: "Graduate", level: 3 },
  { degree: "Graduate Diploma in Law", level: 2 },
  { degree: "Graduation", level: 3 },
  { degree: "HNDip", level: 2 },
  { degree: "HScD", level: 5 },
  { degree: "Higher National Diploma", level: 2 },
  { degree: "Higher National Certificate", level: 1 },
  { degree: "Higher National Diploma", level: 2 },
  { degree: "Integrated Professional Master in Languages", level: 4 },
  { degree: "LL.B", level: 3 },
  { degree: "LL.M", level: 4 },
  { degree: "LLB", level: 3 },
  { degree: "LLD", level: 5 },
  { degree: "LLM", level: 4 },
  { degree: "LittD", level: 5 },
  { degree: "M Phil", level: 4 },
  { degree: "M(Res)", level: 4 },
  { degree: "M.A", level: 4 },
  { degree: "M.A.E", level: 4 },
  { degree: "M.A.Ed", level: 4 },
  { degree: "M.Arch", level: 4 },
  { degree: "M.B.A", level: 4 },
  { degree: "M.C", level: 4 },
  { degree: "M.Ch", level: 4 },
  { degree: "M.Chir", level: 4 },
  { degree: "M.Couns", level: 4 },
  { degree: "M.Des", level: 4 },
  { degree: "M.Design", level: 4 },
  { degree: "M.Ed", level: 4 },
  { degree: "M.Ed.L", level: 4 },
  { degree: "M.Eng", level: 4 },
  { degree: "M.Ent", level: 4 },
  { degree: "M.F.A", level: 4 },
  { degree: "M.Fin", level: 4 },
  { degree: "M.Jur", level: 4 },
  { degree: "M.Mus", level: 4 },
  { degree: "M.Ost", level: 4 },
  { degree: "M.P.Adm", level: 4 },
  { degree: "M.P.H", level: 4 },
  { degree: "M.Phil", level: 4 },
  { degree: "M.S", level: 4 },
  { degree: "M.S.E", level: 4 },
  { degree: "M.S.Ed", level: 4 },
  { degree: "M.Sc", level: 4 },
  { degree: "M.Sci", level: 4 },
  { degree: "M.Soc.Sci", level: 4 },
  { degree: "M.Tech", level: 4 },
  { degree: "M.Th", level: 4 },
  { degree: "M.Vet.Sci", level: 4 },
  // { degree: "MA", level: 4 },
  { degree: "MA by research", level: 4 },
  { degree: "MA(Ed)", level: 4 },
  { degree: "MA(Engl)", level: 4 },
  { degree: "MA(Res)", level: 4 },
  { degree: "MARes", level: 4 },
  { degree: "MASt", level: 4 },
  { degree: "MAc", level: 4 },
  { degree: "MAcc", level: 4 },
  { degree: "MAcy", level: 4 },
  { degree: "MAnth", level: 4 },
  { degree: "MArch", level: 4 },
  { degree: "MBA", level: 4 },
  { degree: "MBBCh", level: 4 },
  { degree: "MBBChir(Cantab)", level: 4 },
  { degree: "MBBS", level: 4 },
  { degree: "MBChB", level: 4 },
  { degree: "MBIOMS", level: 4 },
  { degree: "MBio", level: 4 },
  { degree: "MBioMed", level: 4 },
  { degree: "MBioch", level: 4 },
  { degree: "MBiochem", level: 4 },
  { degree: "MBiol", level: 4 },
  { degree: "MBiolSci", level: 4 },
  { degree: "MBioms", level: 4 },
  { degree: "MBus", level: 4 },
  { degree: "MCA", level: 4 },
  { degree: "MCh", level: 4 },
  { degree: "MCh Orth", level: 4 },
  { degree: "MChD", level: 4 },
  { degree: "MChd", level: 4 },
  { degree: "MChem", level: 4 },
  { degree: "MChemPhys", level: 4 },
  { degree: "MChiro", level: 4 },
  { degree: "MClass", level: 4 },
  { degree: "MClin Res", level: 4 },
  { degree: "MClinDent", level: 4 },
  { degree: "MClinEd", level: 4 },
  { degree: "MClinRes", level: 4 },
  { degree: "MClinSci", level: 4 },
  { degree: "MComp", level: 4 },
  { degree: "MCompPhil", level: 4 },
  { degree: "MCompSci", level: 4 },
  { degree: "MCouns", level: 4 },
  { degree: "MDS", level: 4 },
  { degree: "MDSc", level: 4 },
  { degree: "MDes", level: 4 },
  { degree: "MESci", level: 4 },
  { degree: "MEarthPhys", level: 4 },
  { degree: "MEarthSci", level: 4 },
  { degree: "MEcol", level: 4 },
  { degree: "MEcon", level: 4 },
  { degree: "MEd", level: 4 },
  { degree: "MEng", level: 4 },
  { degree: "MEng", level: 4 },
  { degree: "MEnt", level: 4 },
  { degree: "MEnv", level: 4 },
  { degree: "MEnvSci", level: 4 },
  { degree: "MFA", level: 4 },
  { degree: "MFin", level: 4 },
  { degree: "MGeoPhys", level: 4 },
  { degree: "MGeoSci", level: 4 },
  { degree: "MGeog", level: 4 },
  { degree: "MGeol", level: 4 },
  { degree: "MGeophys", level: 4 },
  { degree: "MGeoscience", level: 4 },
  { degree: "MHist", level: 4 },
  { degree: "MInf", level: 4 },
  { degree: "MInnov", level: 4 },
  { degree: "MJur", level: 4 },
  { degree: "MLang", level: 4 },
  { degree: "MLaw", level: 4 },
  { degree: "MLegSc", level: 4 },
  { degree: "MLibArts", level: 4 },
  { degree: "MLitt", level: 4 },
  { degree: "MMBiol", level: 4 },
  { degree: "MMSPH", level: 4 },
  { degree: "MMSci", level: 4 },
  { degree: "MMarBiol", level: 4 },
  { degree: "MMath", level: 4 },
  { degree: "MMath&Phys", level: 4 },
  { degree: "MMathComp", level: 4 },
  { degree: "MMathCompSci", level: 4 },
  { degree: "MMathPhil", level: 4 },
  { degree: "MMathPhys", level: 4 },
  { degree: "MMedEd", level: 4 },
  { degree: "MMedSci", level: 4 },
  { degree: "MMet", level: 4 },
  { degree: "MMid", level: 4 },
  { degree: "MMkt", level: 4 },
  { degree: "MMus", level: 4 },
  { degree: "MNatSci", level: 4 },
  { degree: "MNeuroSci", level: 4 },
  { degree: "MNurs", level: 4 },
  { degree: "MNursSci", level: 4 },
  { degree: "MNutr", level: 4 },
  { degree: "MOSci", level: 4 },
  { degree: "MOcean", level: 4 },
  { degree: "MOptom", level: 4 },
  { degree: "MOst", level: 4 },
  { degree: "MPA", level: 4 },
  { degree: "MPAc", level: 4 },
  { degree: "MPAcc", level: 4 },
  { degree: "MPAcy", level: 4 },
  { degree: "MPerf", level: 4 },
  { degree: "MPharm", level: 4 },
  { degree: "MPharmSci", level: 4 },
  { degree: "MPharmacol", level: 4 },
  { degree: "MPhil", level: 4 },
  { degree: "MPhyPhil", level: 4 },
  { degree: "MPhys", level: 4 },
  { degree: "MPlan", level: 4 },
  { degree: "MPrac", level: 4 },
  { degree: "MProf", level: 4 },
  { degree: "MPsych", level: 4 },
  { degree: "MRes", level: 4 },
  { degree: "MS", level: 4 },
  { degree: "MSD", level: 4 },
  { degree: "MSPH", level: 4 },
  { degree: "MSSc", level: 4 },
  { degree: "MSW", level: 4 },
  { degree: "MSc", level: 4 },
  { degree: "MSc by research", level: 4 },
  { degree: "MSc(Res)", level: 4 },
  { degree: "MScD", level: 4 },
  { degree: "MScRes", level: 4 },
  { degree: "MSci", level: 4 },
  { degree: "MSt", level: 4 },
  { degree: "MTL", level: 4 },
  { degree: "MTeach", level: 4 },
  { degree: "MTech", level: 4 },
  { degree: "MTh", level: 4 },
  { degree: "MTheol", level: 4 },
  { degree: "MVPH", level: 4 },
  { degree: "MVetPhys", level: 4 },
  { degree: "MVetSci", level: 4 },
  { degree: "MZOOL", level: 4 },
  { degree: "Mag. Jur", level: 4 },
  { degree: "Master of Jurisprudence", level: 4 },
  { degree: "Master in Arts", level: 4 },
  { degree: "Master in Chemistry", level: 4 },
  { degree: "Master in European Business", level: 4 },
  { degree: "Master in Hotel Management", level: 4 },
  { degree: "Master of Accountancy", level: 4 },
  { degree: "Master of Advanced Metallurgy", level: 4 },
  { degree: "Master of Anthropology", level: 4 },
  { degree: "Master of Architecture", level: 4 },
  { degree: "Master of Arts", level: 4 },
  { degree: "Master of Biochemistry", level: 4 },
  { degree: "Master of Biology", level: 4 },
  { degree: "Master of Biomedical Siences", level: 4 },
  { degree: "Master of Business", level: 4 },
  { degree: "Master of Business Administration", level: 4 },
  { degree: "Master of Chemical Physics", level: 4 },
  { degree: "Master of Chiropractic", level: 4 },
  { degree: "Master of Classical Studies", level: 4 },
  { degree: "Master of Clinical Dentistry", level: 4 },
  { degree: "Master of Clinical Education", level: 4 },
  { degree: "Master of Clinical Optometry", level: 4 },
  { degree: "Master of Clinical Research", level: 4 },
  { degree: "Master of Computational Mathematics", level: 4 },
  { degree: "Master of Computer Science and Philosophy", level: 4 },
  { degree: "Master of Computing", level: 4 },
  { degree: "Master of Counselling", level: 4 },
  { degree: "Master of Creative Writing Crime Fiction", level: 4 },
  { degree: "Master of Dental Public Health", level: 4 },
  { degree: "Master of Dental Science", level: 4 },
  { degree: "Master of Dental Surgery", level: 4 },
  { degree: "Master of Design", level: 4 },
  { degree: "Master of Earth Science", level: 4 },
  { degree: "Master of Ecology", level: 4 },
  { degree: "Master of Economics", level: 4 },
  { degree: "Master of Education", level: 4 },
  { degree: "Master of Engineering", level: 4 },
  { degree: "Master of Enterprise", level: 4 },
  { degree: "Master of Environmental Science", level: 4 },
  { degree: "Master of Finance", level: 4 },
  { degree: "Master of Fine Arts", level: 4 },
  { degree: "Master of Geography", level: 4 },
  { degree: "Master of Geology", level: 4 },
  { degree: "Master of Geophysics", level: 4 },
  { degree: "Master of Geoscience", level: 4 },
  { degree: "Master of Health Science", level: 4 },
  { degree: "Master of History", level: 4 },
  { degree: "Master of Innovation", level: 4 },
  { degree: "Master of International Affairs", level: 4 },
  { degree: "Master of Land Economy", level: 4 },
  { degree: "Master of Law", level: 4 },
  { degree: "Master of Laws", level: 4 },
  { degree: "Master of Legal Science", level: 4 },
  { degree: "Master of Letters", level: 4 },
  { degree: "Master of Liberal Arts", level: 4 },
  { degree: "Master of Linguistic Studies", level: 4 },
  { degree: "Master of Marine Biology", level: 4 },
  { degree: "Master of Marine Science", level: 4 },
  { degree: "Master of Marketing", level: 4 },
  { degree: "Master of Materials Science", level: 4 },
  { degree: "Master of Mathematics", level: 4 },
  { degree: "Master of Mathematics and Philosophy", level: 4 },
  { degree: "Master of Mathematics and Physics", level: 4 },
  { degree: "Master of Medical Education", level: 4 },
  { degree: "Master of Medical Science", level: 4 },
  { degree: "Master of Medical Science in Public Health", level: 4 },
  { degree: "Master of Meteorology", level: 4 },
  { degree: "Master of Midwifery", level: 4 },
  { degree: "Master of Museum Practice", level: 4 },
  { degree: "Master of Music", level: 4 },
  { degree: "Master of Music Therapy", level: 4 },
  { degree: "Master of Natural Sciences", level: 4 },
  { degree: "Master of Neuroscience", level: 4 },
  { degree: "Master of Nursing", level: 4 },
  { degree: "Master of Nursing Science", level: 4 },
  { degree: "Master of Nutrition", level: 4 },
  { degree: "Master of Oceanography", level: 4 },
  { degree: "Master of Orthopaedic Surgery", level: 4 },
  { degree: "Master of Osteopathy", level: 4 },
  { degree: "Master of Performance", level: 4 },
  { degree: "Master of Pharmacology", level: 4 },
  { degree: "Master of Pharmacy", level: 4 },
  { degree: "Master of Philosophy", level: 4 },
  { degree: "Master of Physics", level: 4 },
  { degree: "Master of Planning", level: 4 },
  { degree: "Master of Primary Care", level: 4 },
  { degree: "Master of Professional Accountancy", level: 4 },
  { degree: "Master of Professional Practice", level: 4 },
  { degree: "Master of Psychology", level: 4 },
  { degree: "Master of Public Administration", level: 4 },
  { degree: "Master of Public Health", level: 4 },
  { degree: "Master of Public Policy", level: 4 },
  { degree: "Master of Research", level: 4 },
  { degree: "Master of Science", level: 4 },
  { degree: "Master of Science in Dentistry", level: 4 },
  { degree: "Master of Science in Public Health", level: 4 },
  { degree: "Master of Social Science", level: 4 },
  { degree: "Master of Social Work", level: 4 },
  { degree: "Master of Studies", level: 4 },
  { degree: "Master of Surgery", level: 4 },
  { degree: "Master of Teaching and Learning", level: 4 },
  { degree: "Master of Technology degree", level: 4 },
  { degree: "Master of Theology", level: 4 },
  { degree: "Master of Veterinary Medicine", level: 4 },
  { degree: "Master of Veterinary Physiotherapy", level: 4 },
  { degree: "Master of Veterinary Public Health", level: 4 },
  { degree: "Master of Veterinary Sciences", level: 4 },
  { degree: "Master of Veterinary Surgery", level: 4 },
  { degree: "Master of Zoology", level: 4 },
  { degree: "Master's", level: 4 },
  { degree: "Masters", level: 4 },
  { degree: "Masters of Clinical Sciences", level: 4 },
  { degree: "MiF", level: 4 },
  { degree: "Mus.B", level: 3 },
  { degree: "Mus.Bac", level: 3 },
  { degree: "MusD", level: 5 },
  { degree: "Ph.M", level: 4 },
  { degree: "Ph.D", level: 5 },
  { degree: "PhD", level: 5 },
  { degree: "Post Graduate", level: 4 },
  { degree: "Postgraduate", level: 4 },
  { degree: "Professional in Human Resources", level: 3 },
  { degree: "Psy.D", level: 5 },
  { degree: "PsyM", level: 4 },
  { degree: "Sc.B", level: 3 },
  { degree: "Sc.M", level: 4 },
  { degree: "ScD", level: 5 },
  { degree: "Sci.M", level: 4 },
  { degree: "SocScD", level: 5 },
  { degree: "Th.B", level: 3 },
  { degree: "Th.M", level: 4 },
  { degree: "ThD", level: 5 },
  { degree: "Vet.M.B", level: 4 },
  { degree: "Higher Secondary", level: 1 },
  { degree: "Secondary", level: 1 },
  { degree: "10th", level: 1 },
  { degree: "12th", level: 1 },
  { degree: "10TH", level: 1 },
  { degree: "12TH", level: 1 },
  { degree: "Intermediate", level: 1 },
  { degree: "10+2", level: 1 },
  { degree: "High School", level: 1 },
  { degree: "Class XII", level: 1 },
  { degree: "Class X", level: 1 },
  { degree: "PGPM", level: 4 }
];
