module.exports = [
  "year of experience",
  "years of experience",
  "years of relevant",
  "years of related",
  "years of industry",
  "years strong experience",
  "years professional experience",
  "years’ industry experience",
  "years relevant experience",
  "years of work experience",
  "years of overall",
  "years of total",
  "years' experience",
  "years in full stack development",
  "years of hands",
  "years of software development",
  "years of recent experience",
  "years software",
  "years of demonstrated",
  "years of professional",
  "years of IT experience",
  "years of infrastructure engineer",
  "years experience",
  "years in development",
  "years extensive experience",
  "years of",
  "years or more"
];
