module.exports = [
  "developer",
  "engineer",
  "owner",
  "manager",
  "president",
  "director",
  "ceo",
  "teacher",
  "principal",
  "intern",
  "consultant",
  "Lead Talent Acquisition",
  "Talent Acquisition Specialist",
  "Talent Acquisition Executive",
  // "founder",
  "executive",
  "administrator",
  "assistant",
  "sales associate",
  "managing director",
  "chairman",
  "board member",
  "supervisor",
  "account executive",
  "chief executive",
  "customer service representative",
  "cashier",
  "realtor",
  "professor",
  "attorney",
  "receptionist",
  "store manager",
  "secretary",
  "graphic designer",
  "business analyst",
  "analyst",
  "lecturer",
  "designer",
  "trainee",
  "business owner",
  "technician",
  "project coordinator",
  "religious leader",
  // "co-founder",
  "summer intern",
  "waitress",
  "architect",
  "editor",
  "marketing intern",
  "director of operations",
  "recruiter",
  "human resources manager",
  "team lead",
  "programmer",
  "chef",
  "senior vice president",
  "substitute teacher",
  "clerk",
  "doctor",
  "lawyer",
  "management trainee",
  "trainer",
  "phd student",
  "treasurer",
  "physician",
  "educator",
  "Director",
  "Photographer",
  "Author",
  "Copywriter",
  "MERCHANDISER",
];
